# Generated by Django 5.2.7 on 2025-10-29 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-3 code (USA, FRA, JPN)', max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Official country name', max_length=100)),
                ('flag_svg_url', models.URLField(help_text='SVG flag image URL from flagcdn.com', max_length=500)),
                ('flag_png_url', models.URLField(help_text='PNG flag image URL (fallback for older browsers)', max_length=500)),
                ('flag_alt_text', models.TextField(blank=True, help_text='Descriptive text for flag (accessibility)')),
                ('coat_of_arms_svg_url', models.URLField(blank=True, help_text='SVG coat of arms URL (not all countries have one)', max_length=500, null=True)),
                ('coat_of_arms_png_url', models.URLField(blank=True, help_text='PNG coat of arms URL (fallback)', max_length=500, null=True)),
                ('flag_emoji', models.CharField(help_text='Unicode flag emoji (🇺🇸)', max_length=10)),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('area_km2', models.FloatField(help_text='Total area in square kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('highest_point', models.CharField(blank=True, help_text='Highest elevation point (Mt. Everest, etc.)', max_length=100, null=True)),
                ('population', models.BigIntegerField(help_text='Current population estimate', validators=[django.core.validators.MinValueValidator(0)])),
                ('capital', models.CharField(help_text='Capital city name', max_length=100)),
                ('largest_city', models.CharField(help_text='Most populous city (may differ from capital)', max_length=100)),
                ('languages', models.JSONField(default=list, help_text='List of languages: ["English", "Spanish"]')),
                ('religions', models.JSONField(blank=True, help_text='List of major religions', null=True)),
                ('currencies', models.JSONField(default=dict, help_text='Currency info: {"USD": {"name": "US Dollar", "symbol": "$"}}')),
                ('gdp_nominal', models.BigIntegerField(blank=True, help_text='GDP in current USD', null=True)),
                ('gdp_ppp_per_capita', models.IntegerField(blank=True, help_text='GDP per capita adjusted for purchasing power', null=True)),
                ('median_age', models.FloatField(blank=True, help_text='Median age of population', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('life_expectancy', models.FloatField(blank=True, help_text='Average life expectancy in years', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('school_expectancy', models.FloatField(blank=True, help_text='Expected years of schooling', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fertility_rate', models.FloatField(blank=True, help_text='Average births per woman', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('arable_land_percent', models.FloatField(blank=True, help_text='Percentage of land suitable for crops', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('difficulty_tier', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, help_text='Recognition difficulty (MVP: unused, Phase 2: active)', max_length=10, null=True)),
                ('popularity_score', models.IntegerField(default=0, help_text='Algorithm input for tier assignment (search volume, etc.)')),
                ('api_cache_date', models.DateTimeField(auto_now_add=True, help_text='When we last fetched from REST Countries API')),
                ('raw_api_response', models.JSONField(blank=True, help_text='Full JSON from REST Countries API for future flexibility', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'flags_country',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='flags_count_code_1d7ada_idx'), models.Index(fields=['name'], name='flags_count_name_a0cbbf_idx'), models.Index(fields=['difficulty_tier'], name='flags_count_difficu_d2c9fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of this challenge (timezone: America/New_York)', unique=True)),
                ('difficulty_tier', models.CharField(blank=True, help_text='Difficulty tier if using rotation algorithm', max_length=10, null=True)),
                ('selection_algorithm_version', models.CharField(default='v1_random', help_text='Which algorithm selected this country', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(help_text="The country for this day's challenge", on_delete=django.db.models.deletion.PROTECT, related_name='daily_challenges', to='flags.country')),
            ],
            options={
                'db_table': 'flags_dailychallenge',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flag', 'Flag Recognition'), ('capital', 'Capital City'), ('population', 'Population'), ('currency', 'Currency'), ('language', 'Language(s)'), ('area', 'Area Size'), ('largest_city', 'Largest City'), ('continent', 'Continent/Region'), ('highest_point', 'Highest Point'), ('gdp', 'GDP'), ('life_expectancy', 'Life Expectancy')], db_index=True, help_text="What aspect of the country we're asking about", max_length=30)),
                ('format', models.CharField(choices=[('text_input', 'Text Input'), ('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], db_index=True, help_text='How the user should answer', max_length=30)),
                ('question_text', models.TextField(help_text='The actual question shown to user')),
                ('correct_answer', models.JSONField(help_text='Structure depends on format - see Question docstring')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional: hints, explanations, difficulty overrides')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(help_text='Which country this question is about', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flags.country')),
                ('daily_challenge', models.ForeignKey(blank=True, help_text='If this is a daily challenge question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='flags.dailychallenge')),
            ],
            options={
                'db_table': 'flags_question',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(help_text="User's answer - structure matches question format")),
                ('is_correct', models.BooleanField(help_text='Whether the answer was correct')),
                ('explanation', models.TextField(blank=True, help_text='Why the answer was correct/incorrect')),
                ('attempt_number', models.IntegerField(default=1, help_text='Attempt number (1, 2, or 3 for daily challenges)')),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='How long user took to answer (optional)', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Which question this answers', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='flags.question')),
            ],
            options={
                'db_table': 'flags_useranswer',
                'ordering': ['-answered_at'],
            },
        ),
    ]
