# Generated by Django 5.2.7 on 2025-10-29 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(help_text='User who submitted this answer', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dailychallenge',
            index=models.Index(fields=['date'], name='flags_daily_date_93e7bc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'format'], name='flags_quest_categor_99d1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['country'], name='flags_quest_country_e70583_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['daily_challenge'], name='flags_quest_daily_c_679474_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'question'], name='flags_usera_user_id_2effb0_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'is_correct'], name='flags_usera_user_id_951c68_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question'], name='flags_usera_questio_d101a3_idx'),
        ),
    ]
