# Generated by Django 5.2.7 on 2025-11-21 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyTierState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(db_index=True, help_text="Tier name: 'default', 'easy', 'medium', 'hard', or custom", max_length=20)),
                ('cycle_number', models.PositiveIntegerField(default=1, help_text='Current cycle number (increments when all countries shown)')),
                ('cycle_start_date', models.DateField(help_text='When current cycle began')),
                ('last_selection_date', models.DateField(blank=True, help_text='Most recent country selection date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL for global daily challenge, FK for user-specific quiz cycles', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tier_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flags_difficultytierstate',
                'ordering': ['tier', 'user'],
                'unique_together': {('tier', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TierShownCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True, help_text='When this country was selected')),
                ('country', models.ForeignKey(help_text='Country that was shown', on_delete=django.db.models.deletion.CASCADE, to='flags.country')),
                ('tier_state', models.ForeignKey(help_text='Which tier state this belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shown_countries', to='flags.difficultytierstate')),
            ],
            options={
                'db_table': 'flags_tiershowncountry',
                'ordering': ['-shown_at'],
                'unique_together': {('tier_state', 'country')},
            },
        ),
    ]
